# numPy

#### [documentation](https://numpy.org/doc/stable/reference/)

|🍭 [ML](https://www.mediafire.com/file/njc51t2ierhir85/akashdipmahapatraFreeCAD.apk/file) 🍭|🐥 [Pandas](https://akashdip2001.github.io/freecad_app/) 🐥|❌ [numPy](https://engineering-aot.github.io/custom-video-player/freecad_exam.html) ❌|
|-------------------- |-------------------- |-------------------- |

<p float="left">
  <img src="img/numPy_1.jpg" width="100%" />
    <img src="img/numPy_2.jpg" width="100%" />
    <img src="img/numPy_3.jpg" width="100%" />
</p>

In [1]:
import numpy as np

### 1D Array [documentation](https://numpy.org/doc/stable/user/basics.creation.html)

In [2]:
myarr = np.array([3,6,32,7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
#myarr = np.array([3,6,32888888,7], np.int8) => ❌ Memory size < number
myarr = np.array([3,6,32888888,7], np.int32)
myarr

array([       3,        6, 32888888,        7], dtype=int32)

In [5]:
myarr[0]  #1D Array => [ ], 2D Array [ , ]

np.int32(3)

### 2D Array

In [6]:
myarr = np.array([[3,6,32,7]], np.int64)
myarr

array([[ 3,  6, 32,  7]])

In [7]:
myarr[0,1]

np.int64(6)

In [8]:
myarr.dtype

dtype('int64')

### Change the no in Array

In [9]:
myarr[0,1] = 45
myarr

array([[ 3, 45, 32,  7]])

## Array_1) Conversion from other Python structures

In [10]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int64')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,23,53})    #not use Obj => use int or Float => for Mathematical cal...

array({34, 53, 23}, dtype=object)

## Array_2) Intrinsic NumPy array creation functions

In [15]:
zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# 3 in 1
print("Data type:", listarray.dtype)
print("Shape:", listarray.shape)
print("Size:", listarray.size)

Data type: int64
Shape: (3, 3)
Size: 9


In [17]:
rng = np.arange(15)  #arange create => numPy array
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,10,10)    # 1 to 10 => total 10 equally space
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
lspace = np.linspace(1,50,10)   # 1 to 50 => total 10 equally space
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

#### Empty Array

In [20]:
emp = np.empty((4,6))  # 4X6 => Random elemants
emp

array([[ 1.08907377e-311,  6.79453105e-313,  1.08858384e-311,
         6.79453105e-313,  3.25959773e-310, -4.34679076e-311],
       [ 2.75164205e-135, -5.97648350e-311,  1.08730858e+270,
         5.43432418e+279,  6.01433264e+175,  2.79195069e-152],
       [ 7.62873624e+228,  1.49292415e-090,  6.10935453e+223,
         6.19637392e+223,  8.02146756e+165,  1.50761589e+161],
       [ 6.01334642e-154,  2.43567289e-152,  3.81435356e+228,
         8.92892664e+271,  4.77800043e+180,  6.01334515e-154]])

#### Emply Array in Old place (=> Random)
##### np.empty_like([Old_Array-Name])

In [21]:
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

#### identity Matrix

In [22]:
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
ide.shape

(45, 45)

### ReShape (if possible)

In [25]:
arr = np.arange(33)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [26]:
arr.reshape(11, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [27]:
arr.reshape(3, 11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

# But

arr.reshape(3, 10) ❌

### Ravel , 2D => 1D Array

In [28]:
arr = arr.reshape(3, 11)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [29]:
arr.shape

(3, 11)

In [30]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [31]:
arr.shape

(33,)

# Theory

<p float="left">
    <img src="img/numPy_4.jpg" width="100%" />
</p>

In [32]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [33]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

### Sum

In [34]:
ar.sum(axis=0)

array([12,  8,  9])

In [35]:
ar.sum(axis=1)

array([ 6, 15,  8])

### Transpose

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

### flat

In [37]:
ar.flat

In [38]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [39]:
ar.ndim  # no of Dinension

2

In [40]:
ar.size

9

In [41]:
ar.nbytes # Total bite consumes

72

#### Max - Min in Array

In [42]:
one = np.array([1,2,4,888,2]) # Create a 1D Array

In [43]:
one.argmax()

np.int64(3)

In [44]:
one.argmin()

np.int64(0)

In [45]:
one.argsort() # Max => Min

array([0, 1, 4, 2, 3])

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.argmax()  # Max value in the 6th place

np.int64(6)

In [48]:
ar.argmin()

np.int64(8)

In [49]:
ar.argmax(axis=0)  # Max elimants in every Columns

array([2, 1, 1])

In [50]:
ar.argmax(axis=1) # Max elements in every Row

array([2, 2, 0])

In [51]:
ar.argsort(axis=0)  # Max => Min elimants in every Columns

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [52]:
ar.argsort(axis=1)  # Min => Max elimants in every Columns

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

---

In [53]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [54]:
ar.reshape(9, 1 )

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [55]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

# Sum of 2 Array

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ar2 = np.array([[1, 2, 1],
              [4, 0, 6],
              [8, 1, 0]])

In [58]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

# But

In [59]:
[324, 34] + [34, 546]

[324, 34, 34, 546]

# X

In [60]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

# ²√

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

# Sum

In [62]:
ar.sum()

np.int64(29)

# Max - Min

In [63]:
ar.max()

np.int64(7)

In [64]:
ar.min()

np.int64(0)

# Find / Filter

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [67]:
type(np.where(ar>5))

tuple

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [70]:
ar[1, 2] = 0
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

it's give 'tuple' for every Dimension (for every axis)

# Memory Management
### => numPy Array (take size in memory)

In [71]:
import sys

In [72]:
python_array = [0,4,55,2]

In [73]:
numPy_array = np.array(python_array)

In [74]:
sys.getsizeof(1) * len(python_array)

112

In [75]:
numPy_array.itemsize * numPy_array.size

32

### Goohle shearch => numPy array methods & attributes